# Generated by Django 4.1 on 2022-08-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demenagement', '0002_remove_categories_parent_produit_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('numberphone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
